// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceStrategyApp.Models;

#nullable disable

namespace RaceStrategyApp.Migrations
{
    [DbContext(typeof(RaceStrategyContext))]
    [Migration("20250629182021_AutoIncrementBetter")]
    partial class AutoIncrementBetter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("RaceStrategyApp.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOfOpponents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LapCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MandatoryStops")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfLaps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RaceProgressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Refueling")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("SelectedTyres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TerminalDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackWeather")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceProgressId");

                    b.HasIndex("RaceSeriesId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("RaceStrategyApp.Models.RaceProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("RaceId");

                    b.ToTable("RaceProgresses");
                });

            modelBuilder.Entity("RaceStrategyApp.Models.RaceSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RaceSeries");
                });

            modelBuilder.Entity("RaceStrategyApp.Models.Tyre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Compound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TyreDegCoeff")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Tyre");
                });

            modelBuilder.Entity("RaceStrategyApp.Models.Race", b =>
                {
                    b.HasOne("RaceStrategyApp.Models.RaceProgress", null)
                        .WithMany("RaceSnapshots")
                        .HasForeignKey("RaceProgressId");

                    b.HasOne("RaceStrategyApp.Models.RaceSeries", null)
                        .WithMany("Races")
                        .HasForeignKey("RaceSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceStrategyApp.Models.Tyre", b =>
                {
                    b.HasOne("RaceStrategyApp.Models.Race", null)
                        .WithMany("AvailableTyres")
                        .HasForeignKey("RaceId");
                });

            modelBuilder.Entity("RaceStrategyApp.Models.Race", b =>
                {
                    b.Navigation("AvailableTyres");
                });

            modelBuilder.Entity("RaceStrategyApp.Models.RaceProgress", b =>
                {
                    b.Navigation("RaceSnapshots");
                });

            modelBuilder.Entity("RaceStrategyApp.Models.RaceSeries", b =>
                {
                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
