//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 12.7.2025 16:38:50
namespace RaceStrategyApp.ODataClient
{
    /// <summary>
    /// There are no comments for RaceSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RaceSingle")]
    public partial class RaceSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Race>
    {
        /// <summary>
        /// Initialize a new RaceSingle object.
        /// </summary>
        public RaceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RaceSingle object.
        /// </summary>
        public RaceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RaceSingle object.
        /// </summary>
        public RaceSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Race> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Race in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Race")]
    public partial class Race : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Race object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="numberOfLaps">Initial value of NumberOfLaps.</param>
        /// <param name="lapCount">Initial value of LapCount.</param>
        /// <param name="mandatoryStops">Initial value of MandatoryStops.</param>
        /// <param name="numberOfStops">Initial value of NumberOfStops.</param>
        /// <param name="refueling">Initial value of Refueling.</param>
        /// <param name="lastRefuelLap">Initial value of LastRefuelLap.</param>
        /// <param name="position">Initial value of Position.</param>
        /// <param name="amountOfOpponents">Initial value of AmountOfOpponents.</param>
        /// <param name="currentTyre">Initial value of CurrentTyre.</param>
        /// <param name="trackState">Initial value of TrackState.</param>
        /// <param name="damage">Initial value of Damage.</param>
        /// <param name="terminalDamage">Initial value of TerminalDamage.</param>
        /// <param name="trackWeather">Initial value of TrackWeather.</param>
        /// <param name="raceSeriesId">Initial value of RaceSeriesId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Race CreateRace(int ID, 
                    string name, 
                    int numberOfLaps, 
                    int lapCount, 
                    int mandatoryStops, 
                    int numberOfStops, 
                    bool refueling, 
                    int lastRefuelLap, 
                    int position, 
                    int amountOfOpponents, 
                    global::RaceStrategyApp.Models.TyreCompound currentTyre, 
                    global::RaceStrategyApp.Models.TrackState trackState, 
                    bool damage, 
                    bool terminalDamage, 
                    global::RaceStrategyApp.Models.Weather trackWeather, 
                    int raceSeriesId)
        {
            Race race = new Race();
            race.Id = ID;
            race.Name = name;
            race.NumberOfLaps = numberOfLaps;
            race.LapCount = lapCount;
            race.MandatoryStops = mandatoryStops;
            race.NumberOfStops = numberOfStops;
            race.Refueling = refueling;
            race.LastRefuelLap = lastRefuelLap;
            race.Position = position;
            race.AmountOfOpponents = amountOfOpponents;
            race.CurrentTyre = currentTyre;
            race.TrackState = trackState;
            race.Damage = damage;
            race.TerminalDamage = terminalDamage;
            race.TrackWeather = trackWeather;
            race.RaceSeriesId = raceSeriesId;
            return race;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property NumberOfLaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("NumberOfLaps")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NumberOfLaps is required.")]
        public virtual int NumberOfLaps
        {
            get
            {
                return this._NumberOfLaps;
            }
            set
            {
                this.OnNumberOfLapsChanging(value);
                this._NumberOfLaps = value;
                this.OnNumberOfLapsChanged();
                this.OnPropertyChanged("NumberOfLaps");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _NumberOfLaps;
        partial void OnNumberOfLapsChanging(int value);
        partial void OnNumberOfLapsChanged();
        /// <summary>
        /// There are no comments for Property LapCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LapCount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LapCount is required.")]
        public virtual int LapCount
        {
            get
            {
                return this._LapCount;
            }
            set
            {
                this.OnLapCountChanging(value);
                this._LapCount = value;
                this.OnLapCountChanged();
                this.OnPropertyChanged("LapCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _LapCount;
        partial void OnLapCountChanging(int value);
        partial void OnLapCountChanged();
        /// <summary>
        /// There are no comments for Property MandatoryStops in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MandatoryStops")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "MandatoryStops is required.")]
        public virtual int MandatoryStops
        {
            get
            {
                return this._MandatoryStops;
            }
            set
            {
                this.OnMandatoryStopsChanging(value);
                this._MandatoryStops = value;
                this.OnMandatoryStopsChanged();
                this.OnPropertyChanged("MandatoryStops");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _MandatoryStops;
        partial void OnMandatoryStopsChanging(int value);
        partial void OnMandatoryStopsChanged();
        /// <summary>
        /// There are no comments for Property NumberOfStops in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("NumberOfStops")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NumberOfStops is required.")]
        public virtual int NumberOfStops
        {
            get
            {
                return this._NumberOfStops;
            }
            set
            {
                this.OnNumberOfStopsChanging(value);
                this._NumberOfStops = value;
                this.OnNumberOfStopsChanged();
                this.OnPropertyChanged("NumberOfStops");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _NumberOfStops;
        partial void OnNumberOfStopsChanging(int value);
        partial void OnNumberOfStopsChanged();
        /// <summary>
        /// There are no comments for Property Refueling in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Refueling")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Refueling is required.")]
        public virtual bool Refueling
        {
            get
            {
                return this._Refueling;
            }
            set
            {
                this.OnRefuelingChanging(value);
                this._Refueling = value;
                this.OnRefuelingChanged();
                this.OnPropertyChanged("Refueling");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _Refueling;
        partial void OnRefuelingChanging(bool value);
        partial void OnRefuelingChanged();
        /// <summary>
        /// There are no comments for Property LastRefuelLap in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastRefuelLap")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LastRefuelLap is required.")]
        public virtual int LastRefuelLap
        {
            get
            {
                return this._LastRefuelLap;
            }
            set
            {
                this.OnLastRefuelLapChanging(value);
                this._LastRefuelLap = value;
                this.OnLastRefuelLapChanged();
                this.OnPropertyChanged("LastRefuelLap");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _LastRefuelLap;
        partial void OnLastRefuelLapChanging(int value);
        partial void OnLastRefuelLapChanged();
        /// <summary>
        /// There are no comments for Property Position in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Position")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Position is required.")]
        public virtual int Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this.OnPositionChanging(value);
                this._Position = value;
                this.OnPositionChanged();
                this.OnPropertyChanged("Position");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Position;
        partial void OnPositionChanging(int value);
        partial void OnPositionChanged();
        /// <summary>
        /// There are no comments for Property AmountOfOpponents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AmountOfOpponents")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AmountOfOpponents is required.")]
        public virtual int AmountOfOpponents
        {
            get
            {
                return this._AmountOfOpponents;
            }
            set
            {
                this.OnAmountOfOpponentsChanging(value);
                this._AmountOfOpponents = value;
                this.OnAmountOfOpponentsChanged();
                this.OnPropertyChanged("AmountOfOpponents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _AmountOfOpponents;
        partial void OnAmountOfOpponentsChanging(int value);
        partial void OnAmountOfOpponentsChanged();
        /// <summary>
        /// There are no comments for Property SelectedTyres in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SelectedTyres")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SelectedTyres is required.")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<global::RaceStrategyApp.Models.TyreCompound> SelectedTyres
        {
            get
            {
                return this._SelectedTyres;
            }
            set
            {
                this.OnSelectedTyresChanging(value);
                this._SelectedTyres = value;
                this.OnSelectedTyresChanged();
                this.OnPropertyChanged("SelectedTyres");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::RaceStrategyApp.Models.TyreCompound> _SelectedTyres = new global::System.Collections.ObjectModel.ObservableCollection<global::RaceStrategyApp.Models.TyreCompound>();
        partial void OnSelectedTyresChanging(global::System.Collections.ObjectModel.ObservableCollection<global::RaceStrategyApp.Models.TyreCompound> value);
        partial void OnSelectedTyresChanged();
        /// <summary>
        /// There are no comments for Property CurrentTyre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentTyre")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CurrentTyre is required.")]
        public virtual global::RaceStrategyApp.Models.TyreCompound CurrentTyre
        {
            get
            {
                return this._CurrentTyre;
            }
            set
            {
                this.OnCurrentTyreChanging(value);
                this._CurrentTyre = value;
                this.OnCurrentTyreChanged();
                this.OnPropertyChanged("CurrentTyre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::RaceStrategyApp.Models.TyreCompound _CurrentTyre;
        partial void OnCurrentTyreChanging(global::RaceStrategyApp.Models.TyreCompound value);
        partial void OnCurrentTyreChanged();
        /// <summary>
        /// There are no comments for Property TrackState in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TrackState")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TrackState is required.")]
        public virtual global::RaceStrategyApp.Models.TrackState TrackState
        {
            get
            {
                return this._TrackState;
            }
            set
            {
                this.OnTrackStateChanging(value);
                this._TrackState = value;
                this.OnTrackStateChanged();
                this.OnPropertyChanged("TrackState");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::RaceStrategyApp.Models.TrackState _TrackState;
        partial void OnTrackStateChanging(global::RaceStrategyApp.Models.TrackState value);
        partial void OnTrackStateChanged();
        /// <summary>
        /// There are no comments for Property Damage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Damage")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Damage is required.")]
        public virtual bool Damage
        {
            get
            {
                return this._Damage;
            }
            set
            {
                this.OnDamageChanging(value);
                this._Damage = value;
                this.OnDamageChanged();
                this.OnPropertyChanged("Damage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _Damage;
        partial void OnDamageChanging(bool value);
        partial void OnDamageChanged();
        /// <summary>
        /// There are no comments for Property TerminalDamage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TerminalDamage")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TerminalDamage is required.")]
        public virtual bool TerminalDamage
        {
            get
            {
                return this._TerminalDamage;
            }
            set
            {
                this.OnTerminalDamageChanging(value);
                this._TerminalDamage = value;
                this.OnTerminalDamageChanged();
                this.OnPropertyChanged("TerminalDamage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _TerminalDamage;
        partial void OnTerminalDamageChanging(bool value);
        partial void OnTerminalDamageChanged();
        /// <summary>
        /// There are no comments for Property TrackWeather in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TrackWeather")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TrackWeather is required.")]
        public virtual global::RaceStrategyApp.Models.Weather TrackWeather
        {
            get
            {
                return this._TrackWeather;
            }
            set
            {
                this.OnTrackWeatherChanging(value);
                this._TrackWeather = value;
                this.OnTrackWeatherChanged();
                this.OnPropertyChanged("TrackWeather");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::RaceStrategyApp.Models.Weather _TrackWeather;
        partial void OnTrackWeatherChanging(global::RaceStrategyApp.Models.Weather value);
        partial void OnTrackWeatherChanged();
        /// <summary>
        /// There are no comments for Property RaceSeriesId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RaceSeriesId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RaceSeriesId is required.")]
        public virtual int RaceSeriesId
        {
            get
            {
                return this._RaceSeriesId;
            }
            set
            {
                this.OnRaceSeriesIdChanging(value);
                this._RaceSeriesId = value;
                this.OnRaceSeriesIdChanged();
                this.OnPropertyChanged("RaceSeriesId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _RaceSeriesId;
        partial void OnRaceSeriesIdChanging(int value);
        partial void OnRaceSeriesIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RaceSeriesSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RaceSeriesSingle")]
    public partial class RaceSeriesSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RaceSeries>
    {
        /// <summary>
        /// Initialize a new RaceSeriesSingle object.
        /// </summary>
        public RaceSeriesSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RaceSeriesSingle object.
        /// </summary>
        public RaceSeriesSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RaceSeriesSingle object.
        /// </summary>
        public RaceSeriesSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RaceSeries> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Races in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Races")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.Race> Races
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Races == null))
                {
                    this._Races = Context.CreateQuery<global::RaceStrategyApp.Models.Race>(GetPath("Races"));
                }
                return this._Races;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.Race> _Races;
    }
    /// <summary>
    /// There are no comments for RaceSeries in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("RaceSeries")]
    public partial class RaceSeries : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RaceSeries object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="participantCount">Initial value of ParticipantCount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static RaceSeries CreateRaceSeries(int ID, string name, int participantCount)
        {
            RaceSeries raceSeries = new RaceSeries();
            raceSeries.Id = ID;
            raceSeries.Name = name;
            raceSeries.ParticipantCount = participantCount;
            return raceSeries;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ParticipantCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ParticipantCount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ParticipantCount is required.")]
        public virtual int ParticipantCount
        {
            get
            {
                return this._ParticipantCount;
            }
            set
            {
                this.OnParticipantCountChanging(value);
                this._ParticipantCount = value;
                this.OnParticipantCountChanged();
                this.OnPropertyChanged("ParticipantCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ParticipantCount;
        partial void OnParticipantCountChanging(int value);
        partial void OnParticipantCountChanged();
        /// <summary>
        /// There are no comments for Property Races in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Races")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::RaceStrategyApp.Models.Race> Races
        {
            get
            {
                return this._Races;
            }
            set
            {
                this.OnRacesChanging(value);
                this._Races = value;
                this.OnRacesChanged();
                this.OnPropertyChanged("Races");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::RaceStrategyApp.Models.Race> _Races = new global::Microsoft.OData.Client.DataServiceCollection<global::RaceStrategyApp.Models.Race>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRacesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::RaceStrategyApp.Models.Race> value);
        partial void OnRacesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RaceProgressSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RaceProgressSingle")]
    public partial class RaceProgressSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RaceProgress>
    {
        /// <summary>
        /// Initialize a new RaceProgressSingle object.
        /// </summary>
        public RaceProgressSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RaceProgressSingle object.
        /// </summary>
        public RaceProgressSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RaceProgressSingle object.
        /// </summary>
        public RaceProgressSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RaceProgress> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for RaceSnapshots in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RaceSnapshots")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.Race> RaceSnapshots
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RaceSnapshots == null))
                {
                    this._RaceSnapshots = Context.CreateQuery<global::RaceStrategyApp.Models.Race>(GetPath("RaceSnapshots"));
                }
                return this._RaceSnapshots;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.Race> _RaceSnapshots;
    }
    /// <summary>
    /// There are no comments for RaceProgress in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("RaceProgress")]
    public partial class RaceProgress : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RaceProgress object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="raceId">Initial value of RaceId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static RaceProgress CreateRaceProgress(int ID, int raceId)
        {
            RaceProgress raceProgress = new RaceProgress();
            raceProgress.Id = ID;
            raceProgress.RaceId = raceId;
            return raceProgress;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RaceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RaceId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RaceId is required.")]
        public virtual int RaceId
        {
            get
            {
                return this._RaceId;
            }
            set
            {
                this.OnRaceIdChanging(value);
                this._RaceId = value;
                this.OnRaceIdChanged();
                this.OnPropertyChanged("RaceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _RaceId;
        partial void OnRaceIdChanging(int value);
        partial void OnRaceIdChanged();
        /// <summary>
        /// There are no comments for Property RaceSnapshots in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RaceSnapshots")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::RaceStrategyApp.Models.Race> RaceSnapshots
        {
            get
            {
                return this._RaceSnapshots;
            }
            set
            {
                this.OnRaceSnapshotsChanging(value);
                this._RaceSnapshots = value;
                this.OnRaceSnapshotsChanged();
                this.OnPropertyChanged("RaceSnapshots");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::RaceStrategyApp.Models.Race> _RaceSnapshots = new global::Microsoft.OData.Client.DataServiceCollection<global::RaceStrategyApp.Models.Race>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRaceSnapshotsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::RaceStrategyApp.Models.Race> value);
        partial void OnRaceSnapshotsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TyreCompound in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TyreCompound")]
    public enum TyreCompound
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("generic")]
        Generic = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("slick")]
        Slick = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("soft")]
        Soft = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("medium")]
        Medium = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("hard")]
        Hard = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("cutSlick")]
        CutSlick = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("intermediate")]
        Intermediate = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("wet")]
        Wet = 7
    }
    /// <summary>
    /// There are no comments for TrackState in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TrackState")]
    public enum TrackState
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("green")]
        Green = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("FCY")]
        FCY = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("SC")]
        SC = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("localYellow")]
        LocalYellow = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("red")]
        Red = 4
    }
    /// <summary>
    /// There are no comments for Weather in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Weather")]
    public enum Weather
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("dry")]
        Dry = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("damp")]
        Damp = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("intermediate")]
        Intermediate = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("wet")]
        Wet = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("heavyWet")]
        HeavyWet = 4
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::RaceStrategyApp.Models.Race as global::RaceStrategyApp.Models.RaceSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::RaceStrategyApp.ODataClient.RaceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.Race> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::RaceStrategyApp.ODataClient.RaceSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::RaceStrategyApp.Models.Race as global::RaceStrategyApp.Models.RaceSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RaceStrategyApp.ODataClient.RaceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.Race> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RaceStrategyApp.ODataClient.RaceSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::RaceStrategyApp.Models.RaceSeries as global::RaceStrategyApp.Models.RaceSeriesSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::RaceStrategyApp.ODataClient.RaceSeriesSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.RaceSeries> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::RaceStrategyApp.ODataClient.RaceSeriesSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::RaceStrategyApp.Models.RaceSeries as global::RaceStrategyApp.Models.RaceSeriesSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RaceStrategyApp.ODataClient.RaceSeriesSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.RaceSeries> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RaceStrategyApp.ODataClient.RaceSeriesSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::RaceStrategyApp.Models.RaceProgress as global::RaceStrategyApp.Models.RaceProgressSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::RaceStrategyApp.ODataClient.RaceProgressSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.RaceProgress> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::RaceStrategyApp.ODataClient.RaceProgressSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::RaceStrategyApp.Models.RaceProgress as global::RaceStrategyApp.Models.RaceProgressSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RaceStrategyApp.ODataClient.RaceProgressSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.RaceProgress> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RaceStrategyApp.ODataClient.RaceProgressSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "RaceStrategyApp.Models", "RaceStrategyApp.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("RaceStrategyApp.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("RaceStrategyApp.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("RaceStrategyApp.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Race in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Race")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.Race> Race
        {
            get
            {
                if ((this._Race == null))
                {
                    this._Race = base.CreateQuery<global::RaceStrategyApp.Models.Race>("Race");
                }
                return this._Race;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.Race> _Race;
        /// <summary>
        /// There are no comments for RaceSeries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RaceSeries")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.RaceSeries> RaceSeries
        {
            get
            {
                if ((this._RaceSeries == null))
                {
                    this._RaceSeries = base.CreateQuery<global::RaceStrategyApp.Models.RaceSeries>("RaceSeries");
                }
                return this._RaceSeries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.RaceSeries> _RaceSeries;
        /// <summary>
        /// There are no comments for RaceProgress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RaceProgress")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.RaceProgress> RaceProgress
        {
            get
            {
                if ((this._RaceProgress == null))
                {
                    this._RaceProgress = base.CreateQuery<global::RaceStrategyApp.Models.RaceProgress>("RaceProgress");
                }
                return this._RaceProgress;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RaceStrategyApp.Models.RaceProgress> _RaceProgress;
        /// <summary>
        /// There are no comments for Race in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRace(global::RaceStrategyApp.Models.Race race)
        {
            base.AddObject("Race", race);
        }
        /// <summary>
        /// There are no comments for RaceSeries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRaceSeries(global::RaceStrategyApp.Models.RaceSeries raceSeries)
        {
            base.AddObject("RaceSeries", raceSeries);
        }
        /// <summary>
        /// There are no comments for RaceProgress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRaceProgress(global::RaceStrategyApp.Models.RaceProgress raceProgress)
        {
            base.AddObject("RaceProgress", raceProgress);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"OData ServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    // If multiple resource names end with the file name, select the shortest one.
                    var resourcePath = global::System.Linq.Enumerable.First(
                        global::System.Linq.Enumerable.OrderBy(
                            global::System.Linq.Enumerable.Where(assembly.GetManifestResourceNames(), name => name.EndsWith(filePath)),
                            filteredName => filteredName.Length));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
